ALTER USER gbrain WITH BYPASSRLS;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gbrain;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO gbrain;
GRANT ALL PRIVILEGES ON SCHEMA public TO gbrain;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO gbrain;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO gbrain;
